{
 "title": "Geth Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 1 },
   "targets": [
    { "expr": "geth_network_id" }
   ]
  },
  {
   "title": "Current Block",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 1, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_block_number" }
   ]
  },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "geth_load_time_seconds" }
   ]
  },
  {
   "title": "Since Last Block Report",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "geth_block_delta_subjective_seconds"
    }
   ]
  },
  {
   "title": "Last Block Seconds Delta",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 1 },
   "targets": [
    { "expr": "geth_block_delta_seconds" }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_number", "legendFormat": "n" }
   ]
  },
  {
   "title": "Block Uncles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_uncles_count", "legendFormat": "n" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_api_suggested_gas_price / 1000000000"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 3 },
   "targets": [
    { "expr": "geth_network_chain_id" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_block_difficulty", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_limit" }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "geth_block_size_bytes", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Block Time Delta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_delta_seconds", "legendFormat": "sec" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_block_transactions_count", "legendFormat": "Transactions" },
    {
     "expr": "geth_block_token_transfer_count",
     "legendFormat": "token transfers"
    },
    {
     "expr": "geth_block_contract_create_count",
     "legendFormat": "contracts created"
    },
    {
     "expr": "geth_block_value_transfer_count",
     "legendFormat": "value transfers"
    }
   ]
  },
  {
   "title": "Block Transactions Gas Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_price_mean / 1000000000",
     "legendFormat": "gas price mean"
    },
    {
     "expr": "geth_block_gas_price_median / 1000000000",
     "legendFormat": "gas price median"
    }
   ]
  },
  {
   "title": "Block Gas Spend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_spent / 1000000000",
     "legendFormat": "block gas spent"
    }
   ]
  },
  {
   "title": "Transaction Nonces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transaction_nonce_median",
     "legendFormat": "tx nonce med"
    },
    {
     "expr": "geth_block_transaction_nonce_mean",
     "legendFormat": "tx nonce mean"
    },
    {}
   ]
  },
  {
   "title": "ETH Value Transferred",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions_sum_value_transfer"
    }
   ]
  },
  {
   "title": "ETH Value Transfer (hist)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions_sum_value_transfer"
    }
   ]
  },
  {
   "title": "Transaction Nonce Median (hist)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transaction_nonce_median"
    }
   ]
  },
  {
   "title": "Block Transaction Gas Spend (hist)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_spent / 1000000000"
    }
   ]
  },
  {
   "title": "Block Gas Used (hist)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used" }
   ]
  },
  { "title": "Etherbases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Blocks Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 83 },
   "targets": [
    { "expr": "geth_blocks_total" }
   ]
  },
  {
   "title": "Transactions Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 83 },
   "targets": [
    { "expr": "geth_transactions_total" }
   ]
  },
  {
   "title": "Etherbase Block Ratio",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_etherbase_block_ratio", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Etherbase Transaction Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_transaction_ratio",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Block Time Deltas (avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_block_time_delta_seconds",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Block Time Deltas (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_block_time_delta_seconds",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Block Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_etherbase_block_total", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Etherbase Transaction Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_transaction_total",
     "legendFormat": "{{address}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } }
 ]
}