{
 "title": "Scraper",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "scrape_samples_scraped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_samples_scraped" }
   ]
  },
  {
   "title": "scrape_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "scrape_series_added",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_series_added" }
   ]
  }
 ]
}