{
 "title": "Geth Exporter - Etherbases",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Etherbase Sum [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(geth_block_etherbase[5m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(geth_etherbase_count[5m])", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "rate(geth_etherbase_block_10_total[2m])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(geth_etherbase_block_10_total[2m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "rate(geth_etherbase_block_100_total[25m])",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(geth_etherbase_block_100_total[25m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Blocks Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
   "targets": [
    { "expr": "geth_blocks_total" }
   ]
  },
  {
   "title": "Transactions Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 22 },
   "targets": [
    { "expr": "geth_transactions_total" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "max(geth_etherbase_block_10_total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geth_etherbase_block_10_total)",
     "legendFormat": "max etherbase ratio"
    },
    { "expr": "5", "legendFormat": "half" }
   ]
  },
  {
   "title": "Etherbase Block Ratio 10",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_etherbase_block_10_total", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Etherbase Block Ratio 1k",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_block_1000_total",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Block Ratio 100",
   "type": "graph",
   "gridPos": { "h": 22, "w": 13, "x": 11, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_etherbase_block_100_total", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Etherbase Block Ratio 10k",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_block_10000_total",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Transaction Ratio 10k",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_etherbase_transaction_10000_total",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Etherbase Balances (log2)",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_etherbase_balance", "legendFormat": "{{address}}" }
   ]
  }
 ]
}