{
 "title": "Geth Exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "geth_load_time_seconds" }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "targets": [
    { "expr": "geth_exporter_uptime" }
   ]
  },
  {
   "title": "Block Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count(geth_blocks_consecutive_total==0)",
     "legendFormat": "zeroed"
    }
   ]
  },
  {
   "title": "Current Consecutive Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "targets": [
    { "expr": "geth_blocks_consecutive_total" }
   ]
  },
  {
   "title": "Consecutive Block Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "(1-(geth_blocks_skipped_total / geth_blocks_total)) * 100"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Network ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "geth_network_id" }
   ]
  },
  {
   "title": "Chain ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "geth_network_chain_id" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth_api_suggested_gas_price / 1000000000"
    }
   ]
  },
  {
   "title": "Last Block Seconds Delta",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "targets": [
    { "expr": "geth_block_delta_seconds" }
   ]
  },
  {
   "title": "Since Last Block Report",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "geth_block_delta_subjective_seconds"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time(geth_block_difficulty[5m]) / avg_over_time(geth_block_delta_seconds[5m])"
    }
   ]
  },
  {
   "title": "Current Block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth_block_number" }
   ]
  },
  {
   "title": "Block Height Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(geth_block_number[10m])", "legendFormat": "rate" },
    { "expr": "rate(geth_block_number[100m])", "legendFormat": "rate" }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(geth_block_difficulty[5m]) / avg_over_time(geth_block_delta_seconds[5m])"
    },
    {
     "expr": "avg_over_time(geth_block_difficulty[1h]) / avg_over_time(geth_block_delta_seconds[1h])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Block Uncles",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "targets": [
    { "expr": "geth_block_uncles_count", "legendFormat": "n" }
   ]
  },
  {
   "title": "Block Uncles Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(geth_block_uncles_count[10m])",
     "legendFormat": "rate block uncles 10m"
    },
    {
     "expr": "rate(geth_block_uncles_count[100m])",
     "legendFormat": "rate block uncles 100m"
    }
   ]
  },
  {
   "title": "Difficulty | Hashrate (/1e12) | Block TimeDelta",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth_block_difficulty / 1e9 / 1e3",
     "legendFormat": "Difficulty"
    },
    {
     "expr": "(geth_block_difficulty / geth_block_delta_seconds) / 1e9 / 1e3",
     "legendFormat": "Hashrate"
    },
    { "expr": "geth_block_delta_seconds", "legendFormat": "block time delta" },
    {
     "expr": "avg_over_time(geth_block_delta_seconds[10m])",
     "legendFormat": "block time avg [5m]"
    }
   ]
  },
  {
   "title": "1d Avg Block Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "expr": "avg_over_time(geth_block_delta_seconds[1d])"
    }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_limit" }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "geth_block_size_bytes", "legendFormat": "block size bytes" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth_block_transactions_count", "legendFormat": "Transactions" },
    {
     "expr": "geth_block_token_transfer_count",
     "legendFormat": "token transfers"
    },
    {
     "expr": "geth_block_contract_create_count",
     "legendFormat": "contracts created"
    },
    {
     "expr": "geth_block_value_transfer_count",
     "legendFormat": "value transfers"
    },
    {
     "expr": "avg_over_time(geth_block_transactions_count[60m])",
     "legendFormat": "transaction count avg 60m"
    }
   ]
  },
  {
   "title": "Block Transactions Gas Price (/1e9)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_price_mean / 1e9",
     "legendFormat": "gas price mean"
    },
    {
     "expr": "geth_block_gas_price_median / 1e9",
     "legendFormat": "gas price median"
    },
    {
     "expr": "geth_api_suggested_gas_price / 1e9",
     "legendFormat": "api estimate gasprice"
    }
   ]
  },
  {
   "title": "Block Tx Gas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used ", "legendFormat": "gas used" },
    { "expr": "geth_block_gas_spent / 1e9", "legendFormat": "gas spent / 1e9" }
   ]
  },
  {
   "title": "gas_used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used ", "legendFormat": "gas used" },
    {
     "expr": "avg_over_time(geth_block_gas_used[1h])",
     "legendFormat": "avg gas used 1h"
    }
   ]
  },
  {
   "title": "ETH Value Transferred Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions_sum_value_transfer"
    }
   ]
  },
  {
   "title": "Last Tx ETH Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 53 },
   "targets": [
    {
     "expr": "geth_block_transactions_value_median"
    }
   ]
  },
  {
   "title": "60m Tx ETH Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 56 },
   "targets": [
    {
     "expr": "avg_over_time(geth_block_transactions_value_median[60m])"
    }
   ]
  },
  {
   "title": "ETH Value Transfer Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions_value_max",
     "legendFormat": "max"
    },
    {
     "expr": "geth_block_transactions_value_min",
     "legendFormat": "min"
    },
    {
     "expr": "geth_block_transactions_value_mean",
     "legendFormat": "mean"
    },
    {
     "expr": "geth_block_transactions_value_median",
     "legendFormat": "median"
    },
    {
     "expr": "avg_over_time(geth_block_transactions_value_median[60m])",
     "legendFormat": "avg median 60m"
    }
   ]
  },
  {
   "title": "Transaction Nonces",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transaction_nonce_median",
     "legendFormat": "tx nonce med"
    },
    {
     "expr": "geth_block_transaction_nonce_mean",
     "legendFormat": "tx nonce mean"
    },
    {}
   ]
  },
  {
   "title": "Transaction Nonces < 1000",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transaction_nonce_median < 1000",
     "legendFormat": "tx nonce med"
    },
    {
     "expr": "geth_block_transaction_nonce_mean < 1000",
     "legendFormat": "tx nonce mean"
    },
    {}
   ]
  },
  {
   "title": "ETH Value Transfer (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transactions_sum_value_transfer"
    }
   ]
  },
  {
   "title": "Transaction Nonce Median (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_transaction_nonce_median"
    }
   ]
  },
  {
   "title": "Block Transaction Gas Spend (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth_block_gas_spent / 1000000000"
    }
   ]
  },
  {
   "title": "Block Gas Used (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used" }
   ]
  },
  {
   "title": "Block Time Deltas (hist)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_delta_seconds" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } }
 ]
}