{
 "title": "Experimental",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Block Gas, Size, and DB Commits",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used / 10", "legendFormat": "block gas used" },
    { "expr": "geth_block_size_bytes", "legendFormat": "block size bytes" },
    {
     "expr": "rate(chain_account_commits_count[5m]) * 10000000",
     "legendFormat": "account commits count magnified"
    }
   ]
  },
  {
   "title": "Gas Use / Tx Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_used", "legendFormat": "gas used" },
    { "expr": "geth_block_transactions_count", "legendFormat": "transaction count" }
   ]
  },
  {
   "title": "Minimum Gas Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_gas_price_min >= 0", "legendFormat": "gas price min" },
    { "expr": "geth_block_transactions_count", "legendFormat": "txs" },
    {
     "expr": "count(geth_block_gas_price_min == 0)",
     "legendFormat": "0 gas price"
    }
   ]
  },
  {
   "title": "Block Size vs. Transactions Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth_block_size_bytes", "legendFormat": "block size bytes" },
    { "expr": "geth_block_transactions_count", "legendFormat": "block transactions" }
   ]
  }
 ]
}